# Generated by Django 3.2.16 on 2023-01-23 10:21

import app.utils.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=254, null=True)),
                ('created_by', models.CharField(blank=True, max_length=254, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=254, null=True)),
                ('event_type', models.PositiveSmallIntegerField(choices=[(0, 'Birth'), (1, 'Death'), (2, 'Marriage')])),
                ('date', app.utils.fields.UncertainDateField()),
                ('reference', models.URLField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.location')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=254, null=True)),
                ('created_by', models.CharField(blank=True, max_length=254, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=254, null=True)),
                ('forename', models.CharField(help_text='Forename / given name', max_length=20)),
                ('middle_names', models.CharField(blank=True, help_text='Middle names(s)', max_length=50)),
                ('known_as', models.CharField(blank=True, help_text='Known as', max_length=20)),
                ('surname', models.CharField(help_text='Surname', max_length=30)),
                ('maiden_name', models.CharField(blank=True, help_text='Maiden name', max_length=30, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1)),
                ('deceased', models.BooleanField(default=True)),
                ('notes', tinymce.models.HTMLField(blank=True)),
                ('birth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.event')),
                ('death', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.event')),
                ('father', models.ForeignKey(blank=True, limit_choices_to={'gender': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_of_father', to='users.person')),
                ('mother', models.ForeignKey(blank=True, limit_choices_to={'gender': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_of_mother', to='users.person')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['surname', 'forename', 'middle_names', '-birth__date'],
            },
        ),
        migrations.CreateModel(
            name='SurnameVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=254, null=True)),
                ('created_by', models.CharField(blank=True, max_length=254, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=254, null=True)),
                ('canonical', models.CharField(help_text='Canonical surname', max_length=30)),
                ('variant', models.CharField(help_text='Surname variant', max_length=30)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=254, null=True)),
                ('created_by', models.CharField(blank=True, max_length=254, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(upload_to='photos')),
                ('caption', models.TextField(blank=True)),
                ('date', app.utils.fields.UncertainDateField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='locations.location')),
                ('people', models.ManyToManyField(related_name='photos', to='users.Person')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=254, null=True)),
                ('created_by', models.CharField(blank=True, max_length=254, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=254, null=True)),
                ('date', app.utils.fields.UncertainDateField(blank=True, null=True)),
                ('divorced', models.BooleanField(default=False)),
                ('reference', models.URLField(blank=True, null=True)),
                ('husband', models.ForeignKey(limit_choices_to={'gender': 'M'}, on_delete=django.db.models.deletion.CASCADE, related_name='husband_of', to='users.person')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weddings', to='locations.location')),
                ('wife', models.ForeignKey(limit_choices_to={'gender': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='wife_of', to='users.person')),
            ],
            options={
                'ordering': ['husband__surname', 'husband__forename', 'husband__middle_names', 'date'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.person'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=254, null=True)),
                ('created_by', models.CharField(blank=True, max_length=254, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=254, null=True)),
                ('file', models.FileField(upload_to='documents')),
                ('document_type', models.PositiveSmallIntegerField(choices=[(0, 'Birth'), (1, 'Marriage'), (2, 'Death/Burial'), (3, 'Census'), (4, 'Military'), (5, 'Land'), (6, 'Press'), (7, 'Emigration/Citizenship')])),
                ('title', models.CharField(max_length=100)),
                ('people', models.ManyToManyField(related_name='documents', to='users.Person')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
