# Generated by Django 3.2.16 on 2023-01-24 07:40

import app.utils.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=254, null=True)),
                ('created_by', models.CharField(blank=True, max_length=254, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=254, null=True)),
                ('date', app.utils.fields.UncertainDateField(blank=True, null=True)),
                ('divorced', models.BooleanField(default=False, help_text='Pisah')),
                ('reference', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['husband__surname', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=254, null=True)),
                ('created_by', models.CharField(blank=True, max_length=254, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=254, null=True)),
                ('full_name', models.CharField(help_text='Nama Lengkap', max_length=60)),
                ('surname', models.CharField(help_text='Nama Keluarga', max_length=30)),
                ('nickname', models.CharField(help_text='Nama Panggilan', max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1)),
                ('date_of_birth', app.utils.fields.UncertainDateField(blank=True, help_text='YYYY-MM-DD', null=True)),
                ('phone', models.CharField(blank=True, help_text='6281234567890', max_length=15, null=True)),
                ('date_of_death', app.utils.fields.UncertainDateField(blank=True, help_text='YYYY-MM-DD', null=True)),
                ('deceased', models.BooleanField(default=False, help_text='Alm')),
                ('notes', tinymce.models.HTMLField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='locations.address', verbose_name='Tempat Lahir')),
                ('birth_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='locations.city', verbose_name='Tempat Lahir')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='peoples.marriage')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['surname', '-date_of_birth'],
            },
        ),
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=254, null=True)),
                ('created_by', models.CharField(blank=True, max_length=254, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(upload_to='photos')),
                ('caption', models.TextField(blank=True)),
                ('date', app.utils.fields.UncertainDateField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='locations.address')),
                ('people', models.ManyToManyField(related_name='photos', to='peoples.Person')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='marriage',
            name='husband',
            field=models.ForeignKey(limit_choices_to={'gender': 'M'}, on_delete=django.db.models.deletion.CASCADE, related_name='husband_of', to='peoples.person'),
        ),
        migrations.AddField(
            model_name='marriage',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weddings', to='locations.address'),
        ),
        migrations.AddField(
            model_name='marriage',
            name='wife',
            field=models.ForeignKey(limit_choices_to={'gender': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='wife_of', to='peoples.person'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=254, null=True)),
                ('created_by', models.CharField(blank=True, max_length=254, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=254, null=True)),
                ('file', models.FileField(upload_to='documents')),
                ('document_type', models.PositiveSmallIntegerField(choices=[(0, 'Birth'), (1, 'Marriage'), (2, 'Death/Burial'), (3, 'Census'), (4, 'Military'), (5, 'Land'), (6, 'Press'), (7, 'Emigration/Citizenship')])),
                ('title', models.CharField(max_length=100)),
                ('people', models.ManyToManyField(related_name='documents', to='peoples.Person')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
